Move genered-charts/p-mysql to manual-charts-experiments and restore initial values.yaml
p-mysql/tests/test-connection.yaml depend on initial values.yaml which fail helm lint with

```
Linting /root/project/generated-charts/p-mysql
[ERROR] templates/: template: p-mysql/templates/tests/test-connection.yaml:14:59: executing "p-mysql/templates/tests/test-connection.yaml" at <.Values.service.port>: nil pointer evaluating interface {}.port

Error: 1 chart(s) linted, 1 chart(s) failed
```